[package]
name = "gobang-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true
tauri-plugin-opener.workspace = true
serde.workspace = true
serde_json.workspace = true
gobang-core = { path = "../core" }
reqwest.workspace = true
futures-util.workspace = true
log.workspace = true
env_logger.workspace = true
renet2.workspace = true
